### ekf config file ###
# https://github.com/cra-ros-pkg/robot_localization/tree/jazzy-devel
# https://github.com/cra-ros-pkg/robot_localization/blob/jazzy-devel/doc/configuring_robot_localization.rst
# http://docs.ros.org/en/melodic/api/robot_localization/html/state_estimation_nodes.html
# https://github.com/cra-ros-pkg/robot_localization/blob/jazzy-devel/params/ekf.yaml
ekf_filter_node:
    ros__parameters:
      # mode1.yaml
      # for wheel,odom_gps and imu fusion

      frequency: 30.0

      sensor_timeout: 0.1
      two_d_mode: true
      transform_time_offset: 0.0
      transform_timeout: 0.0
      print_diagnostics: true
      publish_tf: true
      #publish_tf: false
      publish_acceleration: false
      # memo nishi 2024.4.29
      # use_control: true If true, the state estimation node will listen to the cmd_vel topic 
      #             for a geometry_msgs/Twist message, and use that to generate an acceleration term. 

      map_frame: map
      odom_frame: odom
      base_link_frame: base_footprint
      #base_link_frame: base_link
      #world_frame: odom           # Defaults to the value of odom_frame if unspecified
      # update by nishi 2024.4.29 
      world_frame: odom           # Defaults to the value of odom_frame if unspecified

      # add by nishi 2025.3.11
      yaw_offset: 0.0
      use_odometry_yaw: true

      #odom0: wheel odometry
      odom0: wheel
      #odom0_config: [true, true, false,
      #              false, false, true,
      #              true , true, false,
      #              false, false, true,
      #              false, false, false]

      # 下記は、OK 
      #odom0_config: [true, true, false,
      #              false, false, true,
      #              false, false, false,
      #              false, false, true,
      #              false, false, false]

      # 下記も、OK みたい
      # chnaged by nishi 2025.3.15
      #odom0_config: [true, true, false,
      #              false, false, true,
      #              false, false, false,
      #              false, false, false,
      #              false, false, false]


      # 下記は?
      # chnaged by nishi 2025.3.16
      #odom0_config: [true, true, false,
      #              true, true, true,
      #              false, false, false,
      #              false, false, false,
      #              false, false, false]

      # chnaged by nishi 2025.7.3
      odom0_config: [true, true, true,
                    false, false, true,
                    false, false, false,
                    false, false, false,
                    false, false, false]


      odom0_queue_size: 10
      #odom0_queue_size: 20
      #odom0_differential: true
      odom0_differential: false
      #odom0_relative: true
      odom0_relative: false

      odom1: odom_gps
      odom1_config: [false, false, false,
                    false, false, false,
                    false, false, false,
                    false, false, false,
                    false, false, false]

      #odom1_config: [true, true, false,
      #              false, false, false,
      #              false, false, false,
      #              false, false, false,
      #              false, false, false]

      imu0: imu0
      #imu0_config: [false, false, false,
      #              false, false, true,
      #              false, false, false,
      #              false, false, true,
      #              true, false, false]

      # 下記設定は、エラーになる。?
      # changed by nishi 2025.3.10
      #imu0_config: [false, false, false,
      #              false, false, true,
      #              false, false, false,
      #              false, false, false,
      #              true, false, false]

      # 下記は、 2025.3.15
      #imu0_config: [false, false, false,
      #              false, false, true,
      #              false, false, false,
      #              false, false, false,
      #              false, false, false]

      # 下記は、? 2025.3.16
      imu0_config: [false, false, false,
                    true, true, true,
                    false, false, false,
                    false, false, false,
                    false, false, false]



      imu0_differential: false  # If using a real robot you might want to set this to true, since usually absolute measurements from real imu's are not very accurate
      # changed by nishi 2025.3.10
      #imu0_differential: true  # If using a real robot you might want to set this to true, since usually absolute measurements from real imu's are not very accurate
      #imu0_relative: true
      imu0_relative: false
      imu0_queue_size: 10
      #imu0_queue_size: 20
      #imu0_pose_rejection_threshold: 0.8                 # Note the difference in parameter names
      # changed by nishi 2025.3.11
      imu0_pose_rejection_threshold: 0.95       # good
      #imu0_pose_rejection_threshold: 1.0        # no good
      #imu0_pose_rejection_threshold: 0.0        #  no good
      imu0_twist_rejection_threshold: 0.8                #
      imu0_linear_acceleration_rejection_threshold: 0.8  #
      imu0_remove_gravitational_acceleration: true

      use_control: false
